name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      # Workaround: Pre-cache upload-artifact@v4
      - name: Cache upload-artifact@v4
        uses: actions/upload-artifact@v4
        if: false

      - uses: actions/checkout@v4

      # Downgraded to avoid v3 dependency
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2  # Downgrade from v3 → v2
