name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write  # Needed for GitHub Pages deployment
      id-token: write  # Needed for OIDC token

    steps:
      - uses: actions/checkout@v4  # Updated from v3 → v4

      - name: Setup Pages
        uses: actions/configure-pages@v4  # Updated from v3 → v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2  # Updated from v1 → v2
        with:
          path: './'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3  # Updated from v2 → v3
