name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      # Explicitly cache upload-artifact@v4 to override any v3 references
      - name: Override upload-artifact@v3 with v4
        uses: actions/upload-artifact@v4
        if: false  # Skip execution, just cache the action

      - uses: actions/checkout@v4

      # Use the latest versions that don't rely on v3
      - name: Setup Pages
        uses: actions/configure-pages@v4  # Updated to v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2  # Updated to v2
        with:
          path: './'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3  # Updated to v3
